### ISSUE TITLE
What is expected input for `save_requests_info`?

### ISSUE THREAD

**Issue by leehach** [adrian-soto/mock-request#4]
In `save_requests_info`, what argument is expected for the input parameter `requests_info`?

The `available_requests.dat` ends up with the `base_url` as well as all keys in the `predicates` dictionary, but I can't identify a response object method that contains this info. Is this dictionary supposed to be constructed by hand?

**Comment by adrian-soto** [comment]
Hey @leehach! 

I've been revamping this repo, getting it ready for a 0.1.0 release. I added examples of those files in the `/tests/files` directory, as well as a jupyter notebook to generate them. Hopefully that clarifies how to use it, but I'm open to feedback (if any).

Closing for now, feel free to reopen.
